LOCAL_SERVER_IP: 127.0.0.1
LISTEN_PORT : 8789
CONTROLLER_SWITCH_INIT_URL: http://127.0.0.1:9876/switch_info
CONTROLLER_SWITCH_TOTP_CODE_VERIFICATION_URL: http://127.0.0.1:9876/totp_code_verification
SWITCH_GRPC_ADDRESS: 127.0.0.1:50052